import { formatDate } from '@/helpers/custom.helpers';

export const signupFormFields = (t) => ([
  {
    id: 'register-username',
    name: 'username',
    fieldType: 'input',
    inputType: 'text',
    label: t('userName'),
    placeholder: 'Enter username',
    isRequired: true,
    className: 'bg-arcAuthInput h-[57px] p-4 text-white text-sm rounded-lg focus:ring-blue-500 block w-full ps-10 p-2.5 dark:placeholder-text-white dark:text-white dark:focus:ring-blue-500',
  },
  {
    id: 'register-email',
    name: 'email',
    fieldType: 'input',
    inputType: 'email',
    label: t('email'),
    placeholder: 'Enter your email',
    isRequired: true,
    className: 'bg-arcAuthInput h-[57px] p-4 text-white text-sm rounded-lg focus:ring-blue-500 block w-full ps-10 p-2.5 dark:placeholder-text-white dark:text-white dark:focus:ring-blue-500',
  },
  {
    id: 'register-password',
    name: 'password',
    fieldType: 'textField',
    inputType: 'password',
    label: t('password'),
    placeholder: 'Enter password',
    isRequired: true,
    className: 'bg-arcAuthInput h-[57px] p-4 text-white text-sm rounded-lg focus:ring-blue-500 block w-full ps-10 p-2.5  dark:placeholder-text-white dark:text-white dark:focus:ring-blue-500',
  },
  {
    id: 'register-confirmPassword',
    name: 'confirmPassword',
    fieldType: 'textField',
    inputType: 'password',
    label: t('confirmPassword'),
    placeholder: 'Confirm password',
    isRequired: true,
    className: 'bg-arcAuthInput h-[57px] p-4 text-white text-sm rounded-lg focus:ring-blue-500 block w-full ps-10 p-2.5   dark:placeholder-text-white dark:text-white dark:focus:ring-blue-500',
  },
  {
    id: 'register-firstName',
    name: 'firstName',
    fieldType: 'textField',
    inputType: 'text',
    label: t('firstName'),
    placeholder: 'Enter first name',
    isRequired: true,
    className: 'bg-arcAuthInput h-[57px] p-4 text-white text-sm rounded-lg focus:ring-blue-500 block w-full ps-10 p-2.5 dark:placeholder-text-white dark:text-white dark:focus:ring-blue-500',
  },
  {
    id: 'register-lastName',
    name: 'lastName',
    fieldType: 'textField',
    inputType: 'text',
    label: t('lastName'),
    placeholder: 'Enter last name',
    isRequired: true,
    className: 'bg-arcAuthInput h-[57px] p-4 text-white text-sm rounded-lg focus:ring-blue-500 block w-full ps-10 p-2.5 dark:placeholder-text-white dark:text-white dark:focus:ring-blue-500',
  },
  {
    id: 'register-dateOfBirth',
    name: 'dateOfBirth',
    fieldType: 'date',
    inputType: 'date',
    label: t('dateOfBirth'),
    placeholder: 'Date of Birth',
    isRequired: true,
    minDate: formatDate(new Date(new Date().setFullYear(new Date().getFullYear() - 200))),
    maxDate: formatDate(new Date(new Date().setFullYear(new Date().getFullYear() - 18))),
    className: 'bg-arcAuthInput h-[57px]  mb-4 p-4 text-white text-sm rounded-lg focus:ring-blue-500 block w-full ps-10 p-2.5  dark:placeholder-text-white dark:text-white dark:focus:ring-blue-500',
  },
  {
    id: 'register-gender',
    name: 'gender',
    fieldType: 'radioGroup',
    inputType: 'radio',
    label: t('gender'),
    isRequired: true,
    optionsList: [{ key: 'male', value: 'Male' }, { key: 'female', value: 'Female' }, { key: 'other', value: 'Other' }],
    className: 'bg-gray-50  text-white text-sm rounded-lg focus:ring-blue-500 block w-full ps-10 p-2.5  dark:bg-gray-700  dark:placeholder-text-white dark:text-white dark:focus:ring-blue-500',
  },
]);

export const loginFormFields = (t) => ([
  {
    id: 'login-email',
    name: 'email',
    fieldType: 'input',
    inputType: 'email',
    label: t('userName'),
    placeholder: 'Enter your email',
    isRequired: true,
    className: 'bg-arcAuthInput h-[57px] p-4  text-white text-sm rounded-lg focus:ring-blue-500 block w-full ps-10 p-2.5   dark:placeholder-text-white dark:text-white dark:focus:ring-blue-500',
  },
  {
    id: 'login-password',
    name: 'password',
    fieldType: 'textField',
    inputType: 'password',
    label: t('password'),
    placeholder: 'Enter password',
    isRequired: true,
    className: 'bg-arcAuthInput h-[57px] p-4  text-white text-sm rounded-lg focus:ring-blue-500 block w-full ps-10 p-2.5   dark:placeholder-text-white dark:text-white dark:focus:ring-blue-500',
  },
]);

export const profileDetailsFields = (t) => ([
  {
    id: 'register-firstName',
    name: 'firstName',
    fieldType: 'textField',
    inputType: 'text',
    label: t('firstName'),
    placeholder: 'Enter first name',
    isRequired: true,
    className: 'h-[57px] bg-gray-50 p-4 text-white text-sm rounded-lg block w-full ps-10 p-2.5  dark:bg-arcHeaderBackground  dark:placeholder-text-white dark:text-white',
  },
  {
    id: 'register-lastName',
    name: 'lastName',
    fieldType: 'textField',
    inputType: 'text',
    label: t('lastName'),
    placeholder: 'Enter last name',
    isRequired: true,
    className: 'h-[57px] bg-gray-50 p-4 text-white text-sm rounded-lg focus:ring-blue-500 block w-full ps-10 p-2.5  dark:bg-arcHeaderBackground dark:placeholder-text-white dark:text-white',
  },
  {
    id: 'register-username',
    name: 'username',
    fieldType: 'input',
    inputType: 'text',
    label: t('userName'),
    placeholder: 'Enter username',
    isRequired: true,
    className: 'h-[57px] bg-gray-50 p-4 text-white text-sm rounded-lg focus:ring-blue-500 block w-full ps-10 p-2.5  dark:bg-arcHeaderBackground dark:placeholder-text-white dark:text-white',
  },
  {
    id: 'register-dateOfBirth',
    name: 'dateOfBirth',
    fieldType: 'date',
    inputType: 'date',
    label: t('dateOfBirth'),
    placeholder: 'Date of Birth',
    isRequired: true,
    minDate: formatDate(new Date(new Date().setFullYear(new Date().getFullYear() - 200))),
    maxDate: formatDate(new Date(new Date().setFullYear(new Date().getFullYear() - 18))),
    className: 'h-[57px] bg-gray-50 mb-4 p-4 text-white text-sm rounded-lg focus:ring-blue-500 block w-full ps-10 p-2.5  dark:bg-arcHeaderBackground  dark:placeholder-text-white dark:text-white',
  },
]);

export const changePasswordFields = (t) => ([
  {
    id: 'register-password',
    name: 'password',
    fieldType: 'textField',
    inputType: 'password',
    label: t('password'),
    placeholder: 'Enter password',
    isRequired: true,
    className: 'h-[57px] bg-gray-50 p-4 text-white text-sm rounded-lg focus:ring-blue-500 block w-full ps-10 p-2.5  dark:bg-arcHeaderBackground dark:placeholder-text-white dark:text-white',
  },
  {
    id: 'register-confirmPassword',
    name: 'confirmPassword',
    fieldType: 'textField',
    inputType: 'password',
    label: t('confirmPassword'),
    placeholder: 'Confirm password',
    isRequired: true,
    className: 'h-[57px] bg-gray-50 p-4 text-white text-sm rounded-lg focus:ring-blue-500 block w-full ps-10 p-2.5  dark:bg-arcHeaderBackground dark:placeholder-text-white dark:text-white',
  },
]);
